### ISSUE TITLE
How do i switch to client side rendering

### ISSUE THREAD

**Issue by saniko** [teamfa/sails-universal-react-starter#5]
Is it modifying the the app.js
global.**SERVER** = true;
global.**CLIENT** = false;

I would like to control the app isomorphism, but I'm not sure I'm changing the right params.

:)

**Comment by Salakar** [comment]
@saniko when a page is loaded first time via the browser - that comes from the server, subsequent requests that followed from links in your app are loaded client side. 

This uses our sails react router hook internally, you can see the docs here: https://github.com/teamfa/sails-hook-react-router#config-api

Note there is a routing preference option which you can set - which applies to all routes.

The globals you mentioned, namely: 

``` javascript
global.SERVER = true;
global.CLIENT = false;
```

are not there for changing - you're meant to use them to detect if the current render is done on the server or client, i.e in your component render method.

Very crude example (obviously you wouldn't get data in render but use comp lifecycle methods instead):

``` javascript
class Kittens extends Component {
    render() {
        if (SERVER) {
             // do something server side specific i.e call your sails models for data
        }

        if (CLIENT) {
            // we are on the client so no models available - call an api for data
        }
    }
}
```

**Comment by Salakar** [comment]
If you'd like this functionality though feel free to do a PR on the router repo, would be fairly easy to add:

Routing preference is used here:
https://github.com/teamfa/sails-hook-react-router/blob/master/src/index.js#L187

You could add a routingPref prop onto route components and read that prop in the`_iterateRouteChildren()` fn and pass that as an arg to the `_addRoute()` fn i linked above.
